In [1]:
import numpy as np

In [6]:
# 定义向量
x = np.array([2, 5, 8])
print(x)
print(x.shape)

[2 5 8]
(3,)


In [7]:
# 1. 向量转置
print(x.T)
print(x.T.shape)

[2 5 8]
(3,)


In [18]:
# 2. 相加
y = np.array([1, 3, 7])
print(x + y)

[ 3  8 15]


In [9]:
# 3. 向量与标量相乘
print(x * 3)

[ 6 15 24]


In [16]:
# 4. 向量与向量相乘（对应位置元素相乘）
print(x * y)

[ 2 15 56]


In [11]:
# 5. 向量点乘
np.dot(x, y)
print(x.dot(y))

73


In [12]:
print(x @ y)

73


In [13]:
# 6. 计算范数
l0_norm = np.linalg.norm(x, ord=0)
print(l0_norm)

3.0


In [15]:
l2_norm = np.linalg.norm(x, ord=2)
print(l2_norm)

9.643650760992955
